// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dev-login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/auth/google/start": {
    params: {};
  };
  "/auth/google/callback": {
    params: {};
  };
  "/auth/microsoft/start": {
    params: {};
  };
  "/auth/microsoft/callback": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/time-clock": {
    params: {};
  };
  "/time-clock/reports": {
    params: {};
  };
  "/time-clock/reports/reports.csv": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/todo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dev-login" | "/logout" | "/auth/google/start" | "/auth/google/callback" | "/auth/microsoft/start" | "/auth/microsoft/callback" | "/dashboard" | "/time-clock" | "/time-clock/reports" | "/time-clock/reports/reports.csv" | "/settings" | "/todo";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/login/route.tsx": {
    id: "routes/login/route";
    page: "/login";
  };
  "./routes/dev-login/route.tsx": {
    id: "routes/dev-login/route";
    page: "/dev-login";
  };
  "./routes/logout/route.ts": {
    id: "routes/logout/route";
    page: "/logout";
  };
  "./routes/auth/google/start.ts": {
    id: "routes/auth/google/start";
    page: "/auth/google/start";
  };
  "./routes/auth/google/callback.ts": {
    id: "routes/auth/google/callback";
    page: "/auth/google/callback";
  };
  "./routes/auth/microsoft/start.ts": {
    id: "routes/auth/microsoft/start";
    page: "/auth/microsoft/start";
  };
  "./routes/auth/microsoft/callback.ts": {
    id: "routes/auth/microsoft/callback";
    page: "/auth/microsoft/callback";
  };
  "./layouts/app-layout.tsx": {
    id: "layouts/app-layout";
    page: "/dashboard" | "/time-clock" | "/time-clock/reports" | "/time-clock/reports/reports.csv" | "/settings" | "/todo";
  };
  "./routes/dashboard/route.tsx": {
    id: "routes/dashboard/route";
    page: "/dashboard";
  };
  "./routes/time-clock/route.tsx": {
    id: "routes/time-clock/route";
    page: "/time-clock";
  };
  "./routes/time-clock/reports/route.tsx": {
    id: "routes/time-clock/reports/route";
    page: "/time-clock/reports";
  };
  "./routes/time-clock/reports/reports.csv/route.tsx": {
    id: "routes/time-clock/reports/reports.csv/route";
    page: "/time-clock/reports/reports.csv";
  };
  "./routes/settings/route.tsx": {
    id: "routes/settings/route";
    page: "/settings";
  };
  "./routes/todo/route.tsx": {
    id: "routes/todo/route";
    page: "/todo";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/login/route": typeof import("./app/./routes/login/route.tsx");
  "routes/dev-login/route": typeof import("./app/./routes/dev-login/route.tsx");
  "routes/logout/route": typeof import("./app/./routes/logout/route.ts");
  "routes/auth/google/start": typeof import("./app/./routes/auth/google/start.ts");
  "routes/auth/google/callback": typeof import("./app/./routes/auth/google/callback.ts");
  "routes/auth/microsoft/start": typeof import("./app/./routes/auth/microsoft/start.ts");
  "routes/auth/microsoft/callback": typeof import("./app/./routes/auth/microsoft/callback.ts");
  "layouts/app-layout": typeof import("./app/./layouts/app-layout.tsx");
  "routes/dashboard/route": typeof import("./app/./routes/dashboard/route.tsx");
  "routes/time-clock/route": typeof import("./app/./routes/time-clock/route.tsx");
  "routes/time-clock/reports/route": typeof import("./app/./routes/time-clock/reports/route.tsx");
  "routes/time-clock/reports/reports.csv/route": typeof import("./app/./routes/time-clock/reports/reports.csv/route.tsx");
  "routes/settings/route": typeof import("./app/./routes/settings/route.tsx");
  "routes/todo/route": typeof import("./app/./routes/todo/route.tsx");
};